set fileencodings=utf-8,gb2312,gb18030,gbk,ucs-bom,cp936,latin1
set enc=utf8
set fencs=utf8,gbk,gb2312,gb18030
set nu
set nowrap
set cursorline
call plug#begin('~/.vim/plugged')
Plug 'Yggdroot/indentLine'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'neoclide/coc.nvim',{'branch':'release'}
call plug#end()
let g:indentLine_char_list=['┆','│']
let g:airline_powerline_fonts=1
let g:airline_theme='luna'
map q :q<CR>
map w :w<CR>
